"""Where the Admin-API identity's private material lives, and the one fingerprint that compares it.

Packet 1246-07. Three things live here and nowhere else: the **path derivation**, the **fingerprint**,
and the **staged replacement** that keeps the old material until a new one has authenticated.

**The path is derived, never supplied.** The integrator supplies a ``secrets_dir``; this module
validates it against the fixed ``OsLayout`` and appends the exact current key filename. It accepts no
caller-selected key path — an override would be an alternate authority wearing a parameter's clothes.

**``crypto.encrypt_machine`` / ``decrypt_machine`` reach ``app_paths`` transitively, and that is
intentional AFTER publication.** Before publication this module performs no decryption at all — the
caller gets ``PrerequisiteRequired`` and the transitive path is never entered. After publication
``app_paths`` resolves the same fixed directory the request was validated against, so reaching it is
not an alternate authority: it is the authority, agreeing with the one already checked.

**The Machine Key is REPLACEABLE and this module does not argue with that** (developer ruling,
2026-08-03, in ``crypto.get_machine_key``). A missing key is regenerated by that existing authority at
the authoritative published path. This module neither refuses a missing key nor recreates one — and
its read-only inspection never calls the resolver whose documented behaviour is to write one.
"""

from __future__ import annotations

import base64
import hashlib
import os
import stat
from dataclasses import dataclass
from pathlib import Path

import yaml

from .admin_identity import LocalMaterial
from .errors import LifecycleError

#: The one registration identifier. Kept as the code has always spelled it; the parent's D10 was
#: amended rather than the identifier renamed, because the JWT `iss` must match the console name
#: exactly and a rename is a credentialled remote mutation a WORKING identity must never trigger.
REGISTRATION_NAME = "CORPUSfm-AdminAPI"

#: The component's own store, under the fixed secrets directory. A distinct name from the legacy
#: `fms_admin_pki.yaml` because this is a different record with a different owner and a different
#: location; nothing reads both, and the conversion of the two development boxes is 1246-10's.
STORE_FILENAME = "admin_identity.yaml"

STORE_FILE_MODE = 0o600
STAGED_SUFFIX = ".staged"


class IdentityStoreError(LifecycleError):
    """The identity store could not be resolved, read or written."""


class SecretsDirRefused(IdentityStoreError):
    """A supplied secrets directory is not the fixed OS location. A refusal, never an override."""


@dataclass(frozen=True)
class StoredIdentity:
    """What the store holds for this installation. One identity, never a per-connection map."""

    registration_name: str
    host: str
    private_pem: bytes

    def public_fingerprint(self) -> str:
        return fingerprint_of_private_pem(self.private_pem)


# ── the fingerprint: ONE algorithm, ONE implementation ───────────────────────

def _der_spki_from_pem(public_pem: str | bytes) -> bytes:
    """Canonical DER SubjectPublicKeyInfo bytes from a public-key PEM of ANY line discipline.

    FileMaker Server returns the registered key with every line break stripped (measured on both
    FMS 26.0.1.68 lanes, 2026-08-04) while a locally generated PEM carries them, so a raw string
    comparison reports a false mismatch on every box. Normalising to DER is therefore a measured
    requirement, not a stylistic preference.
    """
    text = public_pem.decode("ascii") if isinstance(public_pem, (bytes, bytearray)) else public_pem
    body = text.replace("-----BEGIN PUBLIC KEY-----", "").replace("-----END PUBLIC KEY-----", "")
    body = "".join(body.split())
    if not body:
        raise IdentityStoreError("a public key with no body cannot be fingerprinted")
    try:
        der = base64.b64decode(body, validate=True)
    except Exception as exc:                      # noqa: BLE001 - any decode failure is the same fact
        raise IdentityStoreError(f"the public key is not valid base64 PEM content: {exc}") from exc
    # And it must actually BE a SubjectPublicKeyInfo. Base64 alone would hand a fingerprint to any
    # blob between the markers, which is a fingerprint of nothing — and this value gates a deletion.
    from cryptography.hazmat.primitives import serialization

    try:
        serialization.load_der_public_key(der)
    except Exception as exc:                      # noqa: BLE001
        raise IdentityStoreError(
            f"the public key does not parse as a SubjectPublicKeyInfo: {exc}") from exc
    return der


def fingerprint_of_public_pem(public_pem: str | bytes) -> str:
    """``sha256:<64 lowercase hex>`` over canonical DER SubjectPublicKeyInfo bytes."""
    return "sha256:" + hashlib.sha256(_der_spki_from_pem(public_pem)).hexdigest()


def fingerprint_of_private_pem(private_pem: bytes) -> str:
    """The same value, derived from the private half. One implementation, five consumers."""
    from cryptography.hazmat.primitives import serialization

    key = serialization.load_pem_private_key(private_pem, password=None)
    der = key.public_key().public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    return "sha256:" + hashlib.sha256(der).hexdigest()


def public_pem_of_private_pem(private_pem: bytes) -> bytes:
    from cryptography.hazmat.primitives import serialization

    key = serialization.load_pem_private_key(private_pem, password=None)
    return key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    )


# ── path derivation ─────────────────────────────────────────────────────────

def _layout_anchor(layout) -> Path:
    """The deepest directory that contains every one of this layout's own locations.

    **On the shipped POSIX layout that anchor is ``/``, so ``/var``, ``/var/lib`` and everything
    below them ARE walked and checked** — the behaviour is deliberately strict and is not weakened
    here. *(An earlier version of this docstring claimed the opposite, that ancestors like ``/var``
    were exempt because some distributions ship them as symlinks. That reasoning was inverted: the
    layout's five directories live under ``/etc``, ``/var`` and ``/run``, so their common ancestor
    is the filesystem root and nothing is exempt. A box that really did present a symlinked ``/var``
    would refuse — correctly, and visibly, rather than writing a private key through a link nobody
    inspected. Corrected 2026-08-05.)*

    On Windows the five directories share ``C:\\ProgramData\\CORPUSfm``, so that is the anchor and
    only ``secrets`` is walked beneath it.
    """
    dirs = getattr(layout, "all_dirs", None)
    if dirs is None:                  # a layout that describes only the secrets location
        return Path(layout.secrets_dir).parent
    try:
        return Path(os.path.commonpath([str(Path(d)) for d in dirs()]))
    except ValueError:                # pragma: no cover - mixed drives cannot occur in one layout
        return Path(layout.secrets_dir).parent


def _refuse_if_link(path: Path, *, fixed: Path) -> None:
    """``lstat``, never ``stat``: the question is what the NAME is, not what it points at."""
    try:
        st = path.lstat()
    except FileNotFoundError:
        return                        # nothing there yet, so nothing to follow
    except OSError as exc:
        raise SecretsDirRefused(
            f"refusing {fixed}: {path} could not be inspected without following it ({exc})"
        ) from exc
    if stat.S_ISLNK(st.st_mode):
        raise SecretsDirRefused(
            f"refusing {fixed}: {path} is a symbolic link. A lexically correct location that is a "
            "link points somewhere else entirely, and the private key would be written through it."
        )
    attrs = getattr(st, "st_file_attributes", 0)
    if attrs & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0):
        raise SecretsDirRefused(
            f"refusing {fixed}: {path} is a Windows reparse point (junction or symbolic link)"
        )


def validated_secrets_dir(supplied: Path | str, *, layout=None) -> Path:
    """The supplied directory, if and only if it IS the fixed OS secrets location — by NAME and
    by the authority of every component of that name under this layout's own anchor.

    Two independent checks, because either alone is defeated:

    * **Lexical equality** to the fixed ``OsLayout`` path. A different path is a refusal, never an
      override — there is no caller-selected key location.
    * **A non-following ``lstat`` walk** from the layout anchor down. An earlier version compared
      ``candidate.resolve() == fixed.resolve()`` *after* establishing lexical equality, which is
      vacuous: two identical paths always resolve identically, so a symlink AT the fixed path was
      accepted and the private key was written through it (measured, 2026-08-05).

    Neither check can prove the directory is still the same one when the write happens — that is
    ``pinned_secrets_dir``'s job, and it is why writes go through a descriptor.
    """
    from . import os_layout as _os_layout

    resolved_layout = layout or _os_layout.platform_os_layout()
    fixed = Path(resolved_layout.secrets_dir)
    candidate = Path(supplied)
    if candidate != fixed:
        raise SecretsDirRefused(
            f"refusing {candidate}: the identity store lives in the fixed secrets directory "
            f"{fixed}. A supplied location that is not the ruled one is a refusal, not an override."
        )
    anchor = _layout_anchor(resolved_layout)
    try:
        relative = candidate.relative_to(anchor)
    except ValueError:                # pragma: no cover - the anchor contains every layout dir
        relative = None
    walk = anchor
    for name in (relative.parts if relative is not None else ()):
        walk = walk / name
        _refuse_if_link(walk, fixed=fixed)
    return candidate


class PinnedSecretsDir:
    """The validated secrets directory, held open, so later work cannot be redirected.

    On POSIX the directory is opened ``O_DIRECTORY|O_NOFOLLOW`` and every subsequent create, read,
    replace and unlink is descriptor-relative. Swapping the path for a link after validation then
    changes nothing: the descriptor still names the directory that was checked, and the next
    operation to re-validate refuses at the open.

    On Windows there is no ``dir_fd`` support in CPython, so operations are path-based and the
    protection of that path is the ACL policy ``lifecycle.protection`` applies. **Live proof of the
    Windows half is 1246-10's**, and this docstring is the one place that is said, rather than a
    silent assumption that the two platforms are equally covered.
    """

    __slots__ = ("path", "_fd")

    def __init__(self, path: Path, fd: int | None):
        self.path = path
        self._fd = fd

    @property
    def fd(self) -> int | None:
        return self._fd

    def _kwargs(self) -> dict:
        return {"dir_fd": self._fd} if self._fd is not None else {}

    def _name(self, filename: str):
        return filename if self._fd is not None else str(self.path / filename)

    def read_bytes(self, filename: str) -> bytes:
        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        fd = os.open(self._name(filename), flags, **self._kwargs())
        try:
            chunks = []
            while True:
                chunk = os.read(fd, 65536)
                if not chunk:
                    return b"".join(chunks)
                chunks.append(chunk)
        finally:
            os.close(fd)

    def write_private(self, filename: str, data: bytes) -> None:
        flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
        fd = os.open(self._name(filename), flags, STORE_FILE_MODE, **self._kwargs())
        try:
            os.write(fd, data)
            os.fsync(fd)
        finally:
            os.close(fd)

    def exists(self, filename: str) -> bool:
        try:
            os.stat(self._name(filename), follow_symlinks=False, **self._kwargs())
            return True
        except (FileNotFoundError, NotADirectoryError):
            return False

    def replace(self, source: str, target: str) -> None:
        if self._fd is not None:
            os.replace(source, target, src_dir_fd=self._fd, dst_dir_fd=self._fd)
        else:                          # pragma: no cover - Windows path, proven live by 1246-10
            os.replace(str(self.path / source), str(self.path / target))

    def unlink(self, filename: str) -> None:
        os.unlink(self._name(filename), **self._kwargs())

    def close(self) -> None:
        if self._fd is not None:
            os.close(self._fd)
            self._fd = None

    def __enter__(self) -> "PinnedSecretsDir":
        return self

    def __exit__(self, *exc) -> None:
        self.close()


def pinned_secrets_dir(supplied: Path | str, *, layout=None,
                       create: bool = False) -> PinnedSecretsDir:
    """Validate, then PIN. Every mutation of the store goes through the returned handle."""
    from corpusfm.core import secure_fs

    path = validated_secrets_dir(supplied, layout=layout)
    if not _dir_fd_supported():        # pragma: no cover - Windows, proven live by 1246-10
        if create:
            secure_fs.secure_dir(path)
        return PinnedSecretsDir(path, None)
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    try:
        fd = os.open(str(path), flags)
    except FileNotFoundError:
        if not create:
            raise
        secure_fs.secure_dir(path)
        # Re-validate after creating: the walk above proved what was there BEFORE the mkdir.
        validated_secrets_dir(supplied, layout=layout)
        fd = os.open(str(path), flags)
    except OSError as exc:
        # ELOOP (a symlink at the fixed path) and ENOTDIR both land here. Either way the name we
        # validated is not a directory we may open without following something.
        raise SecretsDirRefused(
            f"refusing {path}: the fixed secrets directory could not be opened without following "
            f"a link ({exc})"
        ) from exc
    try:
        pinned = os.fstat(fd)
        named = os.lstat(str(path))
    except OSError as exc:             # pragma: no cover - the descriptor is already open
        os.close(fd)
        raise SecretsDirRefused(f"refusing {path}: it could not be re-inspected ({exc})") from exc
    if (pinned.st_dev, pinned.st_ino) != (named.st_dev, named.st_ino):
        # The name was replaced between the walk and the open. The descriptor is the safe object,
        # but the DISAGREEMENT is the fact worth refusing on: something is moving this directory.
        os.close(fd)
        raise SecretsDirRefused(
            f"refusing {path}: the directory that name refers to changed while it was being "
            "validated; nothing was written"
        )
    return PinnedSecretsDir(path, fd)


def _dir_fd_supported() -> bool:
    return (
        os.open in getattr(os, "supports_dir_fd", set())
        and os.unlink in getattr(os, "supports_dir_fd", set())
        and hasattr(os, "O_DIRECTORY")
    )


def store_path(secrets_dir: Path | str, *, layout=None) -> Path:
    return validated_secrets_dir(secrets_dir, layout=layout) / STORE_FILENAME


def staged_path(secrets_dir: Path | str, *, layout=None) -> Path:
    return validated_secrets_dir(secrets_dir, layout=layout) / (STORE_FILENAME + STAGED_SUFFIX)


def machine_key_path(secrets_dir: Path | str, *, layout=None) -> Path:
    """``<validated secrets_dir>/<crypto.MACHINE_KEY_FILENAME>`` — no caller-selected path.

    The FILENAME comes from ``crypto`` so there is one authority for what the file is called; the
    DIRECTORY comes from the validated request so there is one authority for where it lives. The
    no-old-name rule is ``crypto``'s and is not restated here: ``machine.key`` only, never a
    ``server.key`` fallback.
    """
    from corpusfm.core import crypto

    return validated_secrets_dir(secrets_dir, layout=layout) / crypto.MACHINE_KEY_FILENAME


def machine_key_present(secrets_dir: Path | str, *, layout=None) -> bool:
    """Does the key file EXIST? A read-only question, answered without the resolver.

    ``crypto.get_machine_key()`` writes a fresh key when the file is absent — correct behaviour under
    its own ruling, and exactly why a *diagnostic* must not call it. A diagnostic that provisions is
    not a diagnostic.
    """
    return machine_key_path(secrets_dir, layout=layout).exists()


def store_exists(secrets_dir: Path | str, *, layout=None) -> bool:
    """Carried evidence. A file-system observation, never a decryption outcome."""
    pinned = _pinned_or_none(secrets_dir, layout=layout)
    if pinned is None:
        return False
    with pinned:
        return pinned.exists(STORE_FILENAME)


def _pinned_or_none(secrets_dir: Path | str, *, layout=None) -> "PinnedSecretsDir | None":
    """A pinned handle, or ``None`` when the secrets directory itself is not there yet.

    A REFUSAL still propagates. "The directory does not exist" and "the directory is not the one
    this installation may write to" are different facts and only the first is ordinary.
    """
    try:
        return pinned_secrets_dir(secrets_dir, layout=layout)
    except FileNotFoundError:
        return None


# ── read / classify / write ─────────────────────────────────────────────────

def _read_raw(pinned: PinnedSecretsDir, filename: str) -> dict:
    text = pinned.read_bytes(filename).decode("utf-8")
    data = yaml.safe_load(text) or {}
    if not isinstance(data, dict):
        raise IdentityStoreError(f"{pinned.path / filename} does not hold a mapping")
    return data


def classify_local_material(secrets_dir: Path | str, *, layout=None) -> LocalMaterial:
    """The definitive local classification. Callable ONLY after the prerequisite holds.

    Returns ``ABSENT`` when no store file is there, ``PRESENT_USABLE`` when it decrypts and a private
    key loads, ``PRESENT_UNUSABLE`` when it is there and does not, and ``UNREADABLE`` when the
    location itself could not be read. **It never returns ``UNCLASSIFIED``** — that value means the
    prerequisite is unmet, which is the caller's fact, not this function's.
    """
    pinned = _pinned_or_none(secrets_dir, layout=layout)
    if pinned is None:
        return LocalMaterial.ABSENT
    with pinned:
        try:
            if not pinned.exists(STORE_FILENAME):
                return LocalMaterial.ABSENT
            raw = _read_raw(pinned, STORE_FILENAME)
        except OSError:
            return LocalMaterial.UNREADABLE
        except IdentityStoreError:
            return LocalMaterial.PRESENT_UNUSABLE
        except Exception:                         # noqa: BLE001 - a malformed store is present-unusable
            return LocalMaterial.PRESENT_UNUSABLE
        blob = raw.get("private_key_enc")
        if not blob:
            return LocalMaterial.PRESENT_UNUSABLE
        if str(raw.get("registration_name") or REGISTRATION_NAME) != REGISTRATION_NAME:
            # A store naming a DIFFERENT registration is corrupt evidence, not a second identity:
            # there is one registration per installation and its name is fixed. Classifying it
            # unusable is what stops that name reaching the wire, because a usable classification is
            # the only thing that authorizes an authentication attempt.
            return LocalMaterial.PRESENT_UNUSABLE
        try:
            _decrypt_material(blob)
        except Exception:                         # noqa: BLE001 - a wrong Machine Key lands here
            return LocalMaterial.PRESENT_UNUSABLE
        return LocalMaterial.PRESENT_USABLE


def _decrypt_material(blob: str) -> bytes:
    from corpusfm.core.crypto import decrypt_machine

    return decrypt_machine(base64.b64decode(blob))


def load(secrets_dir: Path | str, *, layout=None) -> StoredIdentity | None:
    """The stored identity, or ``None`` when nothing usable is there."""
    pinned = _pinned_or_none(secrets_dir, layout=layout)
    if pinned is None:
        return None
    with pinned:
        try:
            raw = _read_raw(pinned, STORE_FILENAME)
            blob = raw.get("private_key_enc")
            if not blob:
                return None
            return StoredIdentity(
                registration_name=str(raw.get("registration_name") or REGISTRATION_NAME),
                host=str(raw.get("host") or "localhost"),
                private_pem=_decrypt_material(blob),
            )
        except Exception:                         # noqa: BLE001 - unusable is not an exception here
            return None


def _encoded(identity: StoredIdentity) -> bytes:
    from corpusfm.core.crypto import encrypt_machine

    payload = {
        "registration_name": identity.registration_name,
        "host": identity.host,
        "private_key_enc": base64.b64encode(encrypt_machine(identity.private_pem)).decode("ascii"),
    }
    return yaml.safe_dump(payload, default_flow_style=False).encode("utf-8")


def read_store_bytes(secrets_dir: Path | str, *, layout=None) -> bytes | None:
    """The store's ENCRYPTED bytes, verbatim, or ``None`` when there is no store.

    A before-image is taken and restored as bytes so nothing is re-encrypted on the way through —
    a restore that re-derives the ciphertext is a re-encryption, and a re-encryption that fails
    leaves an operation with no way back.
    """
    pinned = _pinned_or_none(secrets_dir, layout=layout)
    if pinned is None:
        return None
    with pinned:
        try:
            return pinned.read_bytes(STORE_FILENAME)
        except (FileNotFoundError, NotADirectoryError):
            return None


def write_store_bytes(secrets_dir: Path | str, raw: bytes, *, layout=None) -> Path:
    """Restore a before-image verbatim. The counterpart of ``read_store_bytes``."""
    with pinned_secrets_dir(secrets_dir, layout=layout, create=True) as pinned:
        pinned.write_private(STORE_FILENAME, raw)
        return pinned.path / STORE_FILENAME


def stage(secrets_dir: Path | str, identity: StoredIdentity, *, layout=None) -> Path:
    """Write new material BESIDE the existing store. The old bytes are untouched.

    This is the whole of "never delete the last working local identity before its replacement
    authenticates": staging is a create, promotion is a rename, and a failed replacement leaves the
    original exactly where it was.
    """
    with pinned_secrets_dir(secrets_dir, layout=layout, create=True) as pinned:
        pinned.write_private(STORE_FILENAME + STAGED_SUFFIX, _encoded(identity))
        return pinned.path / (STORE_FILENAME + STAGED_SUFFIX)


def promote_staged(secrets_dir: Path | str, *, layout=None) -> Path:
    """Replace the store with the staged material. Called ONLY after the new pair authenticated."""
    with pinned_secrets_dir(secrets_dir, layout=layout) as pinned:
        staged = STORE_FILENAME + STAGED_SUFFIX
        if not pinned.exists(staged):
            raise IdentityStoreError(f"nothing staged at {pinned.path / staged} to promote")
        pinned.replace(staged, STORE_FILENAME)
        return pinned.path / STORE_FILENAME


def discard_staged(secrets_dir: Path | str, *, layout=None) -> bool:
    """Remove staged material a failed operation left behind. The store is never touched."""
    pinned = _pinned_or_none(secrets_dir, layout=layout)
    if pinned is None:
        return False
    with pinned:
        try:
            pinned.unlink(STORE_FILENAME + STAGED_SUFFIX)
            return True
        except (FileNotFoundError, NotADirectoryError):
            return False


def save(secrets_dir: Path | str, identity: StoredIdentity, *, layout=None) -> Path:
    """Write the store directly. For a box that holds nothing yet — there is nothing to preserve."""
    with pinned_secrets_dir(secrets_dir, layout=layout, create=True) as pinned:
        pinned.write_private(STORE_FILENAME, _encoded(identity))
        return pinned.path / STORE_FILENAME


def remove_local(secrets_dir: Path | str, *, layout=None) -> bool:
    """Remove the store. Reached only after a verified remote removal, or on an FMS-absent box."""
    pinned = _pinned_or_none(secrets_dir, layout=layout)
    if pinned is None:
        return False
    with pinned:
        try:
            pinned.unlink(STORE_FILENAME)
            return True
        except (FileNotFoundError, NotADirectoryError):
            return False


__all__ = [
    "IdentityStoreError",
    "PinnedSecretsDir",
    "REGISTRATION_NAME",
    "STORE_FILENAME",
    "SecretsDirRefused",
    "StoredIdentity",
    "classify_local_material",
    "discard_staged",
    "pinned_secrets_dir",
    "read_store_bytes",
    "write_store_bytes",
    "fingerprint_of_private_pem",
    "fingerprint_of_public_pem",
    "load",
    "machine_key_path",
    "machine_key_present",
    "promote_staged",
    "public_pem_of_private_pem",
    "remove_local",
    "save",
    "stage",
    "staged_path",
    "store_exists",
    "store_path",
    "validated_secrets_dir",
]
